### ISSUE TITLE
Enable ACPI-enabled U-boot build when Uboot is provided by the BSP layer

### ISSUE THREAD

**Issue by alext-mkrs** [westeri/meta-acpi#11]
Following up on our discussion in https://github.com/westeri/meta-acpi/pull/7, summary [here](https://github.com/westeri/meta-acpi/pull/7#issuecomment-362898523).

Adding U-Boot overrides/appends for enabling ACPI build (and removing this piece from meta-intel-edison), just for Edison and Galileo Gen2 as the first step. See also #10

**Comment by andy-shev** [comment]
Upstream U-Boot from 2020.07 is a first complete solution which enables ACPI by default for Edison, so no need to have special recipe for U-Boot, we may just add it here, but do we really need it right now?

@htot can you revisit issues in this repository and update the status? I'm not familiar with Yocto and I have no idea what happened for the last almost 3 years...

**Comment by htot** [comment]
I can only speak for edison. Right now we have in meta-acpi:
```
├── classes
│   └── edk2.bbclass
├── conf
│   ├── layer.conf
│   └── machine
│       ├── galileo.conf
│       ├── include
│       │   └── acpi.inc
│       ├── joule.conf
│       ├── minnowboard.conf
│       └── minnowboard-max.conf
├── COPYING.MIT
├── README
├── README.sources
├── recipes-bsp
│   ├── acpica
│   │   └── acpica_20190215.bb
│   ├── acpi-tables
│   │   ├── acpi-tables.bb
│   │   ├── files
│   │   │   ├── acpi-tables-load
│   │   │   ├── acpi-tables-load.service
│   │   │   └── edison
│   │   │       └── acpi-tables-load
│   │   └── samples
│   │       ├── edison
...
│   │       ├── galileo
...
│   │       ├── joule
...
│   │       ├── minnowboard
...
│   │       └── minnowboard-max
...
│   └── edk2
│       └── edk2_UDK2015.bb
├── recipes-core
│   └── acpidump
│       └── acpidump.bb
└── recipes-kernel
    └── linux
        ├── files
        │   ├── defconfig
        │   ├── galileo.cfg
        │   └── minnowboard.cfg
        └── linux-kernel.bb
```
Under machine we don't have edison defined, that is because we have it currently `meta-intel-edison/meta-intel-edison-bsp/conf/machine/edison.conf`.
`meta-intel-edison/meta-intel-edison-bsp` is also the recipe currently supplying u-boot and linux (5.6). The linux recipe from meta-acpi is not used (4.4) and could be removed, unless there are  other users.
Other recipies provided by this layer:

- acpidump - we are not using it, but afaikt there are no other yocto layers supplying this recipe, so we should not remove. It might need updating though.
- edk2 - we are not using this, I have no idea about its status, or what it does or who uses it.
- acpica - openembedded-core (zeus) supplies 20190816, we have 20190215. So we are really only supplying a newer acpica to users (edison, galileo, minnow) when they are building a version of acpica that predates zeus. 
- acpi-tables - we have recipies using this, and even specialized acpi-tables-load here for edison.

I think at the time you objected against trying to get edison kernel and u-boot into `meta-acpi`. And currently I agree. Kernel and U-Boot don't belong here, and we should probably clean the kernel already here out.

Imho this is a good central place to have acpi table examples, and possibly acpi tools that can't be found in yocto. And certainly documentation for acpi beginners to learn how to write tables.

**Comment by andy-shev** [comment]
Based on the comment from @htot and my own thought the U-Boot build can be done in certain layer without touching or involving meta-acpi. Closing as **won't fix**.
